server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mabaoying1/springcloud-config.git #github仓库上面的git仓库名字
          search-paths: cloud-config
      #读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #注册进eureka

#rabbit相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: mabaoying
    password: 123456

#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'  #凡是暴露监控、刷新的都要有actuator依赖，bus-refresh就是actuator的刷新操作
